### PR TITLE
Example Json response added to create account endpoint

### PR DESCRIPTION
**Pull request by KBbitsP**
Hi @reshmabidikar @pierre @sbrossie 

This is related to https://github.com/killbill/technical-support/issues/91. 

Raising this one to get more clarity about this task. I removed all the responses present for Shell, Java, Python, Ruby and instead added another tab named  Example JSON response. Please confirm if I understood it correctly.

### CODE REVIEW

**Comment by KBbitsP** [comment]
Hi @reshmabidikar yes I checked Stripe website and they basically have a dropdown to select the query language( php, java, python etc. ) but the response shown each time is the same. So I though of adding it as a tab, not sure how it will render in the docs. Is there a way to preview it?

**Comment by reshmabidikar** [comment]
> Is there a way to preview it

I'm not sure, I'll let @pierre and @sbrossie review.

**Comment by pierre** [comment]
You could build the docs locally:

```
bundle exec middleman build --clean
bundle exec middleman server
```

If it doesn't work (Ruby...), feel free also to just merge it to see how it looks. Easy to revert.

Agreed that it would be nice not to duplicate. In case it doesn't render too nicely, maybe @piyushkalasariya or @jabezX could do some CSS magic 🧙 ?

**Comment by KBbitsP** [comment]
Hi @reshmabidikar @pierre I made more changes to the some more endpoints in the Account section. Also tried to build the docs locally, but was not able to build it. I think we should merge these changes to check how it showing up.

**Comment by pierre** [comment]
What kind of error are you getting?

This is what I see:
image
image


So, it works (as it's shared among all responses), but there is no syntax highlighting. Try with pre-fixing `json` before each code block:

```
> Example Response:
```json
```

**Review by pierre — APPROVED** [review]
Merging - it'll be easier to review that way 😄

**Pull request merged**
